services:
    test_app:
        build:
            context: docker/
            dockerfile: Dockerfile

        ports:
            - '${APP_PORT:-80}:80'
        environment:

            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'

        volumes:
            - '.:/var/www/html'
        networks:
            - testWork
        depends_on:
            - mysql
        container_name: testWorkPlatforma_app
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'laravel'
            MYSQL_USER: 'sail'
            MYSQL_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        networks:
            - testWork
        container_name: testWorkPlatforma_bd
networks:
  testWork:
    driver: bridge
